apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jimwhere-cert
  namespace: jimwhere
spec:
  secretName: jimwhere-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  dnsNames:
    - jimwhere.local
