apiVersion: v1
kind: Service
metadata:
  name: jimwhere-backend
  namespace: jimwhere
spec:
  type: NodePort
  selector:
    app: jimwhere-backend
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30081
