apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jimwhere-ingress
  namespace: jimwhere
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jimwhere.local
      secretName: jimwhere-tls
  rules:
    - host: jimwhere.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jimwhere-frontend
                port:
                  number: 80
          - path: /api/v1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: jimwhere-backend
                port:
                  number: 8088
